
package nl.bkwi.suwiml.diensten.bijstandsregelingen.v0500;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Bijstandsregelingen-v0500", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500", wsdlLocation = "file:/Users/haiko/IdeaProjects/suwinet-simulator-ritense/src/main/resources/suwinet/Bijstandsregelingen/Diensten/Bijstandsregelingen/v0500-b04/Impl/BKWI.wsdl")
public class BijstandsregelingenV0500
    extends Service
{

    private static final URL BIJSTANDSREGELINGENV0500_WSDL_LOCATION;
    private static final WebServiceException BIJSTANDSREGELINGENV0500_EXCEPTION;
    private static final QName BIJSTANDSREGELINGENV0500_QNAME = new QName("http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500", "Bijstandsregelingen-v0500");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/haiko/IdeaProjects/suwinet-simulator-ritense/src/main/resources/suwinet/Bijstandsregelingen/Diensten/Bijstandsregelingen/v0500-b04/Impl/BKWI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIJSTANDSREGELINGENV0500_WSDL_LOCATION = url;
        BIJSTANDSREGELINGENV0500_EXCEPTION = e;
    }

    public BijstandsregelingenV0500() {
        super(__getWsdlLocation(), BIJSTANDSREGELINGENV0500_QNAME);
    }

    public BijstandsregelingenV0500(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIJSTANDSREGELINGENV0500_QNAME, features);
    }

    public BijstandsregelingenV0500(URL wsdlLocation) {
        super(wsdlLocation, BIJSTANDSREGELINGENV0500_QNAME);
    }

    public BijstandsregelingenV0500(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIJSTANDSREGELINGENV0500_QNAME, features);
    }

    public BijstandsregelingenV0500(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BijstandsregelingenV0500(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BijstandsregelingenInfo
     */
    @WebEndpoint(name = "BrokerProductie")
    public BijstandsregelingenInfo getBrokerProductie() {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500", "BrokerProductie"), BijstandsregelingenInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BijstandsregelingenInfo
     */
    @WebEndpoint(name = "BrokerProductie")
    public BijstandsregelingenInfo getBrokerProductie(WebServiceFeature... features) {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500", "BrokerProductie"), BijstandsregelingenInfo.class, features);
    }

    /**
     * 
     * @return
     *     returns BijstandsregelingenInfo
     */
    @WebEndpoint(name = "BrokerIntegratietest")
    public BijstandsregelingenInfo getBrokerIntegratietest() {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500", "BrokerIntegratietest"), BijstandsregelingenInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BijstandsregelingenInfo
     */
    @WebEndpoint(name = "BrokerIntegratietest")
    public BijstandsregelingenInfo getBrokerIntegratietest(WebServiceFeature... features) {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500", "BrokerIntegratietest"), BijstandsregelingenInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIJSTANDSREGELINGENV0500_EXCEPTION!= null) {
            throw BIJSTANDSREGELINGENV0500_EXCEPTION;
        }
        return BIJSTANDSREGELINGENV0500_WSDL_LOCATION;
    }

}
