
package nl.bkwi.suwiml.diensten.bijstandsregelingen.v0500;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BijstandsregelingenInfo", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    nl.bkwi.suwiml.diensten.bijstandsregelingen.v0500.ObjectFactory.class,
    nl.bkwi.suwiml.fwi.v0205.ObjectFactory.class,
    nl.bkwi.suwiml.basisschema.v0801.ObjectFactory.class
})
public interface BijstandsregelingenInfo {


    /**
     * 
     * @param parameters
     * @return
     *     returns nl.bkwi.suwiml.diensten.bijstandsregelingen.v0500.BijstandsregelingenInfoResponse
     * @throws AanvraagNietOk
     */
    @WebMethod(operationName = "BijstandsregelingenInfo")
    @WebResult(name = "BijstandsregelingenInfoResponse", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500", partName = "parameters")
    public BijstandsregelingenInfoResponse bijstandsregelingenInfo(
        @WebParam(name = "BijstandsregelingenInfo", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/Bijstandsregelingen/v0500", partName = "parameters")
        BijstandsregelingenInfo_Type parameters)
        throws AanvraagNietOk
    ;

}
