
package nl.bkwi.suwiml.diensten.duodossierpersoongsd.v0300;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DUODossierPersoonGSD-v0300", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300", wsdlLocation = "file:/Users/paul/denhaag/suwitense/src/main/resources/suwinet/DUODossierPersoonGSD/Diensten/DUODossierPersoonGSD/v0300-b01/Impl/BKWI.wsdl")
public class DUODossierPersoonGSDV0300
    extends Service
{

    private static final URL DUODOSSIERPERSOONGSDV0300_WSDL_LOCATION;
    private static final WebServiceException DUODOSSIERPERSOONGSDV0300_EXCEPTION;
    private static final QName DUODOSSIERPERSOONGSDV0300_QNAME = new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300", "DUODossierPersoonGSD-v0300");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/paul/denhaag/suwitense/src/main/resources/suwinet/DUODossierPersoonGSD/Diensten/DUODossierPersoonGSD/v0300-b01/Impl/BKWI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DUODOSSIERPERSOONGSDV0300_WSDL_LOCATION = url;
        DUODOSSIERPERSOONGSDV0300_EXCEPTION = e;
    }

    public DUODossierPersoonGSDV0300() {
        super(__getWsdlLocation(), DUODOSSIERPERSOONGSDV0300_QNAME);
    }

    public DUODossierPersoonGSDV0300(WebServiceFeature... features) {
        super(__getWsdlLocation(), DUODOSSIERPERSOONGSDV0300_QNAME, features);
    }

    public DUODossierPersoonGSDV0300(URL wsdlLocation) {
        super(wsdlLocation, DUODOSSIERPERSOONGSDV0300_QNAME);
    }

    public DUODossierPersoonGSDV0300(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DUODOSSIERPERSOONGSDV0300_QNAME, features);
    }

    public DUODossierPersoonGSDV0300(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DUODossierPersoonGSDV0300(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DUOInfo
     */
    @WebEndpoint(name = "BrokerProductie")
    public DUOInfo getBrokerProductie() {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300", "BrokerProductie"), DUOInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DUOInfo
     */
    @WebEndpoint(name = "BrokerProductie")
    public DUOInfo getBrokerProductie(WebServiceFeature... features) {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300", "BrokerProductie"), DUOInfo.class, features);
    }

    /**
     * 
     * @return
     *     returns DUOInfo
     */
    @WebEndpoint(name = "BrokerIntegratietest")
    public DUOInfo getBrokerIntegratietest() {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300", "BrokerIntegratietest"), DUOInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DUOInfo
     */
    @WebEndpoint(name = "BrokerIntegratietest")
    public DUOInfo getBrokerIntegratietest(WebServiceFeature... features) {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300", "BrokerIntegratietest"), DUOInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DUODOSSIERPERSOONGSDV0300_EXCEPTION!= null) {
            throw DUODOSSIERPERSOONGSDV0300_EXCEPTION;
        }
        return DUODOSSIERPERSOONGSDV0300_WSDL_LOCATION;
    }

}
