
package nl.bkwi.suwiml.diensten.duodossierpersoongsd.v0300;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DUOInfo", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    nl.bkwi.suwiml.diensten.duodossierpersoongsd.v0300.ObjectFactory.class,
    nl.bkwi.suwiml.fwi.v0205.ObjectFactory.class
})
public interface DUOInfo {


    /**
     * 
     * @param parameters
     * @return
     *     returns nl.bkwi.suwiml.diensten.duodossierpersoongsd.v0300.DUOPersoonsInfoResponse
     * @throws AanvraagNietOk
     */
    @WebMethod(operationName = "DUOPersoonsInfo")
    @WebResult(name = "DUOPersoonsInfoResponse", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300", partName = "parameters")
    public DUOPersoonsInfoResponse duoPersoonsInfo(
        @WebParam(name = "DUOPersoonsInfo", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/DUODossierPersoonGSD/v0300", partName = "parameters")
        DUOPersoonsInfo parameters)
        throws AanvraagNietOk
    ;

}
