
package nl.bkwi.suwiml.diensten.duodossierstudiefinancieringgsd.v0200;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DUODossierStudiefinancieringGSD-v0200", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/DUODossierStudiefinancieringGSD/v0200", wsdlLocation = "file:/Users/paul/denhaag/suwitense/src/main/resources/suwinet/DUODossierStudiefinancieringGSD/Diensten/DUODossierStudiefinancieringGSD/v0200-b01/Impl/BKWI.wsdl")
public class DUODossierStudiefinancieringGSDV0200
    extends Service
{

    private static final URL DUODOSSIERSTUDIEFINANCIERINGGSDV0200_WSDL_LOCATION;
    private static final WebServiceException DUODOSSIERSTUDIEFINANCIERINGGSDV0200_EXCEPTION;
    private static final QName DUODOSSIERSTUDIEFINANCIERINGGSDV0200_QNAME = new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierStudiefinancieringGSD/v0200", "DUODossierStudiefinancieringGSD-v0200");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/paul/denhaag/suwitense/src/main/resources/suwinet/DUODossierStudiefinancieringGSD/Diensten/DUODossierStudiefinancieringGSD/v0200-b01/Impl/BKWI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DUODOSSIERSTUDIEFINANCIERINGGSDV0200_WSDL_LOCATION = url;
        DUODOSSIERSTUDIEFINANCIERINGGSDV0200_EXCEPTION = e;
    }

    public DUODossierStudiefinancieringGSDV0200() {
        super(__getWsdlLocation(), DUODOSSIERSTUDIEFINANCIERINGGSDV0200_QNAME);
    }

    public DUODossierStudiefinancieringGSDV0200(WebServiceFeature... features) {
        super(__getWsdlLocation(), DUODOSSIERSTUDIEFINANCIERINGGSDV0200_QNAME, features);
    }

    public DUODossierStudiefinancieringGSDV0200(URL wsdlLocation) {
        super(wsdlLocation, DUODOSSIERSTUDIEFINANCIERINGGSDV0200_QNAME);
    }

    public DUODossierStudiefinancieringGSDV0200(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DUODOSSIERSTUDIEFINANCIERINGGSDV0200_QNAME, features);
    }

    public DUODossierStudiefinancieringGSDV0200(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DUODossierStudiefinancieringGSDV0200(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DUOInfo
     */
    @WebEndpoint(name = "BrokerProductie")
    public DUOInfo getBrokerProductie() {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierStudiefinancieringGSD/v0200", "BrokerProductie"), DUOInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DUOInfo
     */
    @WebEndpoint(name = "BrokerProductie")
    public DUOInfo getBrokerProductie(WebServiceFeature... features) {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierStudiefinancieringGSD/v0200", "BrokerProductie"), DUOInfo.class, features);
    }

    /**
     * 
     * @return
     *     returns DUOInfo
     */
    @WebEndpoint(name = "BrokerIntegratietest")
    public DUOInfo getBrokerIntegratietest() {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierStudiefinancieringGSD/v0200", "BrokerIntegratietest"), DUOInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DUOInfo
     */
    @WebEndpoint(name = "BrokerIntegratietest")
    public DUOInfo getBrokerIntegratietest(WebServiceFeature... features) {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/DUODossierStudiefinancieringGSD/v0200", "BrokerIntegratietest"), DUOInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DUODOSSIERSTUDIEFINANCIERINGGSDV0200_EXCEPTION!= null) {
            throw DUODOSSIERSTUDIEFINANCIERINGGSDV0200_EXCEPTION;
        }
        return DUODOSSIERSTUDIEFINANCIERINGGSDV0200_WSDL_LOCATION;
    }

}
