
package nl.bkwi.suwiml.diensten.rdwdossiergsd.v0200;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "RDWDossierGSD-v0200", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/RDWDossierGSD/v0200", wsdlLocation = "file:/Users/paul/denhaag/suwitense/src/main/resources/suwinet/Diensten/RDWDossierGSD/v0200-b02/Impl/BKWI.wsdl")
public class RDWDossierGSDV0200
    extends Service
{

    private static final URL RDWDOSSIERGSDV0200_WSDL_LOCATION;
    private static final WebServiceException RDWDOSSIERGSDV0200_EXCEPTION;
    private static final QName RDWDOSSIERGSDV0200_QNAME = new QName("http://bkwi.nl/SuwiML/Diensten/RDWDossierGSD/v0200", "RDWDossierGSD-v0200");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/paul/denhaag/suwitense/src/main/resources/suwinet/Diensten/RDWDossierGSD/v0200-b02/Impl/BKWI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RDWDOSSIERGSDV0200_WSDL_LOCATION = url;
        RDWDOSSIERGSDV0200_EXCEPTION = e;
    }

    public RDWDossierGSDV0200() {
        super(__getWsdlLocation(), RDWDOSSIERGSDV0200_QNAME);
    }

    public RDWDossierGSDV0200(WebServiceFeature... features) {
        super(__getWsdlLocation(), RDWDOSSIERGSDV0200_QNAME, features);
    }

    public RDWDossierGSDV0200(URL wsdlLocation) {
        super(wsdlLocation, RDWDOSSIERGSDV0200_QNAME);
    }

    public RDWDossierGSDV0200(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RDWDOSSIERGSDV0200_QNAME, features);
    }

    public RDWDossierGSDV0200(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RDWDossierGSDV0200(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RDW
     */
    @WebEndpoint(name = "BrokerProductie")
    public RDW getBrokerProductie() {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/RDWDossierGSD/v0200", "BrokerProductie"), RDW.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RDW
     */
    @WebEndpoint(name = "BrokerProductie")
    public RDW getBrokerProductie(WebServiceFeature... features) {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/RDWDossierGSD/v0200", "BrokerProductie"), RDW.class, features);
    }

    /**
     * 
     * @return
     *     returns RDW
     */
    @WebEndpoint(name = "BrokerIntegratietest")
    public RDW getBrokerIntegratietest() {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/RDWDossierGSD/v0200", "BrokerIntegratietest"), RDW.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RDW
     */
    @WebEndpoint(name = "BrokerIntegratietest")
    public RDW getBrokerIntegratietest(WebServiceFeature... features) {
        return super.getPort(new QName("http://bkwi.nl/SuwiML/Diensten/RDWDossierGSD/v0200", "BrokerIntegratietest"), RDW.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RDWDOSSIERGSDV0200_EXCEPTION!= null) {
            throw RDWDOSSIERGSDV0200_EXCEPTION;
        }
        return RDWDOSSIERGSDV0200_WSDL_LOCATION;
    }

}
