
package nl.bkwi.suwiml.diensten.svbdossierpersoongsd.v0200;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SVBInfo", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/SVBDossierPersoonGSD/v0200")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    nl.bkwi.suwiml.diensten.svbdossierpersoongsd.v0200.ObjectFactory.class,
    nl.bkwi.suwiml.fwi.v0205.ObjectFactory.class
})
public interface SVBInfo {


    /**
     * 
     * @param parameters
     * @return
     *     returns nl.bkwi.suwiml.diensten.svbdossierpersoongsd.v0200.SVBPersoonsInfoResponse
     * @throws AanvraagNietOk
     */
    @WebMethod(operationName = "SVBPersoonsInfo")
    @WebResult(name = "SVBPersoonsInfoResponse", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/SVBDossierPersoonGSD/v0200", partName = "parameters")
    public SVBPersoonsInfoResponse svbPersoonsInfo(
        @WebParam(name = "SVBPersoonsInfo", targetNamespace = "http://bkwi.nl/SuwiML/Diensten/SVBDossierPersoonGSD/v0200", partName = "parameters")
        SVBPersoonsInfo parameters)
        throws AanvraagNietOk
    ;

}
